### PR TITLE
Concurrent forall in test units

### PR DESCRIPTION
**Pull request by GavinMendelGleason**
Hello, I've added this minor patch to plunit to enable test blocks to run tests concurrently. We use plunit in our CI/CD and we've managed to get a big speedup in testing stage which has grown to a substantial amount of time in our build process. 

I think the changes are relatively self-contained and understandable, let me know what you think.

We are currently using a compatibility package to provide this functionality in TerminusDB.

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Looks good.  I'm happy to merge.  I do wonder whether or not it might be a better idea to run the blocks concurrently though.   The reasoning would be that blocks are more likely to be independent.   I do have several blocks where the individual tests use the same global dynamic state.   What was your reasoning to do it this way?

**Comment by GavinMendelGleason** [comment]
Your idea makes a lot of sense but writing the code for the progress monitoring looked much more complicated!  I suppose you could simply print out each test as it completes rather than give the "...." output and do it this way instead. We're not too pushed about the output so if that suits better we could change it.

**Comment by JanWielemaker** [comment]
I guess we can learn from ctest.   That prints the tests started and the test completed and if a test fails the possible output from that test (must be enabled).    Using ctest is b.t.w. also how I speedup the tests for SWI-Prolog itself.  There are about 70 "ctest tests", each of which runs multiple PlUnit tests (varying from a few to hundreds as there are stress tests that typically take some time and simple behavior tests that typically take very short).

I'll give this some more thought.   I do like the idea of concurrent testing.

**Comment by GavinMendelGleason** [comment]
Yarg! I forgot to declare the various dynamic predicates as "dynamic" instead of thread local!

**Comment by JanWielemaker** [comment]
Seems there are indeed problems, but probably the other way around, no?   Notably the collect predicates such as passed/5, etc. are all defined as thread-local which means they are asserted in the thread running the test and not picked up by the coordinating thread at the end of the test result.

This may need some more thinking ...

**Comment by rrooij** [comment]
Yeah we are currently looking at how we can patch the predicates dynamically as well. We tried the following:

```prolog
:- redefine_system_predicate(plunit:passed(_,_,_,_,_)).
:- redefine_system_predicate(plunit:failed(_,_,_,_)).
:- redefine_system_predicate(plunit:failed_assertion(_,_,_,_,_,_,_)).
:- redefine_system_predicate(plunit:blocked(_,_,_,_)).
:- redefine_system_predicate(plunit:sto(_,_,_,_)).
:- redefine_system_predicate(plunit:fixme(_,_,_,_,_)).

:- dynamic
    plunit:passed/5,                       % Unit, Test, Line, Det, Time
    plunit:failed/4,                       % Unit, Test, Line, Reason
    plunit:failed_assertion/7,             % Unit, Test, Line, ALoc, STO, Reason, Goal
    plunit:blocked/4,                      % Unit, Test, Line, Reason
    plunit:sto/4,                          % Unit, Test, Line, Results
    plunit:fixme/5.                        % Unit, Test, Line, Reason, Status
```

Which gives the error:

```
Thread 1 (main): foreign predicate system:redefine_system_predicate/1 did not clear exception: 
	error(permission_error(modify,thread_local_procedure,plunit:passed/5),context(system:redefine_system_predicate/1,_29558))
Thread 1 (main): foreign predicate system:redefine_system_predicate/1 did not clear exception: 
	error(permission_error(modify,thread_local_procedure,plunit:failed/4),context(system:redefine_system_predicate/1,_2142))
Thread 1 (main): foreign predicate system:redefine_system_predicate/1 did not clear exception: 
	error(permission_error(modify,thread_local_procedure,plunit:failed_assertion/7),context(system:redefine_system_predicate/1,_2938))
Thread 1 (main): foreign predicate system:redefine_system_predicate/1 did not clear exception: 
	error(permission_error(modify,thread_local_procedure,plunit:blocked/4),context(system:redefine_system_predicate/1,_3590))
Thread 1 (main): foreign predicate system:redefine_system_predicate/1 did not clear exception: 
	error(permission_error(modify,thread_local_procedure,plunit:sto/4),context(system:redefine_system_predicate/1,_4242))
Thread 1 (main): foreign predicate system:redefine_system_predicate/1 did not clear exception: 
	error(permission_error(modify,thread_local_procedure,plunit:fixme/5),context(system:redefine_system_predicate/1,_4942))
```

Apparently, this is unpatchable.

**Comment by JanWielemaker** [comment]
Yes.  You cannot change thread local predicates to shared dynamic AFAIK.   The only solution that does work is a term_expansion/2 rule to rewrite the directive (and make sure you load it before loading plunit.pl).   I guess you are trying a work-around so you can distribute with the latest release?  Will you propose a patch to plunit.pl to make it work for all of us?

**Comment by rrooij** [comment]
If we get it fixed, we will submit a decent PR of course! And yes, we are trying to find a way to run the latest plunit on the stable SWI Prolog.

**Comment by JanWielemaker** [comment]
> And yes, we are trying to find a way to run the latest plunit on the stable SWI Prolog by patching it in.

Best options I see: use term_expansion/2 to rewrite stuff or temporarily distribute a local copy of plunit.pl with TerminusDB and make sure it is before the system library on the `library` path.

**Pull request merged**
